Countries--Cities.WEB/Models/CountryViewModel.cs
namespace Countries__Cities.WEB.Models
{
    public class CountryViewModel : BaseViewModel   
    {

        public string capital { get; set; }

    }
}

Countries--Cities.WEB/Controllers/CountryController.cs
using AutoMapper;
using Countries__Cities.Core.Concrete;
using Countries__Cities.Core.DTOs;
using Countries__Cities.WEB.Filters;
using Countries__Cities.WEB.Models;
using Countries__Cities.WEB.Services;
using Countries__Cities.WEB.Validations;
using FluentValidation.Results;
using Microsoft.AspNetCore.Mvc;

namespace Countries__Cities.WEB.Controllers
{
    public class CountryController : Controller
    {

        private readonly APICountryService _countryService;
        private readonly IMapper _mapper;

        public CountryController(APICountryService countryService, IMapper mapper)
        {
            _countryService = countryService;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _countryService.GetAllAsync());
        }


        [HttpGet]
        public IActionResult SaveCountry()
        {

            return View();

        }

        [HttpPost]
        public async Task<IActionResult> SaveCountry(CountryViewModel countryViewModel)
        {

            string[] validFileTypes = { "gif", "jpg", "png" };
            bool isValidType = false;

            CountryViewModelValidation countryViewModelValidator = new CountryViewModelValidation();
            ValidationResult validationResult = countryViewModelValidator.Validate(countryViewModel);

            if (validationResult.IsValid)
            {

                var resource = Directory.GetCurrentDirectory();
                var extension = Path.GetExtension(countryViewModel.image.FileName);

                for (int i = 0; i < validFileTypes.Length; i++)
                {
                    if (extension == "." + validFileTypes[i])
                    {
                        isValidType = true;
                        break;
                    }
                }

                if (!isValidType)
                {
                    ViewBag.Message = "Lutfen png,jpg ve gif dosyasi yukleyin!";

                    return View();
                }

                var imagename = Guid.NewGuid() + extension;
                var saveLocation = resource + "/wwwroot/countryimage/" + imagename;
                var stream = new FileStream(saveLocation, FileMode.Create);
                await countryViewModel.image.CopyToAsync(stream);

                countryViewModel.imageUrl = imagename;

                await _countryService.SaveAsync(_mapper.Map<CountryDTO>(countryViewModel));


                return RedirectToAction(nameof(Index));

            }
            else
            {

                foreach (var item in validationResult.Errors)
                {

                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
   
                }

            }

            return View();

        }

        [ServiceFilter(typeof(NotFoundFilter<Country>))]
        [HttpGet]
        public async Task<IActionResult> UpdateCountry(int id)
        {
            var country = await _countryService.GetByIdAsync(id);

            ViewBag.imageUrl = country.imageUrl;

            return View(country);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateCountry(CountryViewModel countryViewModel)
        {

            string[] validFileTypes = { "gif", "jpg", "png" };
            bool isValidType = false;

            CountryViewModelValidation countryViewModelValidator = new CountryViewModelValidation();
            ValidationResult validationResult = countryViewModelValidator.Validate(countryViewModel);

            if (validationResult.IsValid)
            {

                if (countryViewModel.image != null)
                {

                    var resource = Directory.GetCurrentDirectory();
                    var extension = Path.GetExtension(countryViewModel.image.FileName);

                    for (int i = 0; i < validFileTypes.Length; i++)
                    {
                        if (extension == "." + validFileTypes[i])
                        {
                            isValidType = true;
                            break;
                        }
                    }

                    if (!isValidType)
                    {
                        ViewBag.Message = "Lutfen png,jpg ve gif dosyasi yukleyin!";

                        return View();
                    }

                    var imagename = Guid.NewGuid() + extension;
                    var saveLocation = resource + "/wwwroot/countryimage/" + imagename;
                    var stream = new FileStream(saveLocation, FileMode.Create);
                    await countryViewModel.image.CopyToAsync(stream);

                    countryViewModel.imageUrl = imagename;

                }

                await _countryService.UpdateAsync(_mapper.Map<CountryDTO>(countryViewModel));

                return RedirectToAction(nameof(Index));

            }
            else
            {

                foreach (var item in validationResult.Errors)
                {

                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                    ViewBag.Message = item.ErrorMessage;

                }

            }


            return View(countryViewModel);

        }
 
      

        [ServiceFilter(typeof(NotFoundFilter<Country>))]
        public async Task<IActionResult> Remove(int id)
        {
            await _countryService.RemoveAsync(id);
            return RedirectToAction(nameof(Index));
        }


 
    }
}

Countries--Cities.WEB/Views/Country/Index.cshtml
@using Countries__Cities.WEB.Models
@model List<CountryWithCityViewModel>


@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}

<div class="col-lg-12 grid-margin stretch-card">
                <div class="card">
                  <div class="card-body">
                    <h4 class="card-title">Ülkeler</h4>
                   
                    <table class="table table-hover">
                      <thead>
                        <tr>
                          <th>ID</th>
                          <th>Ülke Adı</th>
                          <th>Ülke Nüfusu</th>
                          <th>Başkenti</th>
                          <th>Ülke Bayrağı</th>
                          <th>İşlemler</th>
           
                        </tr>
                      </thead>
                      <tbody>
                       @foreach (var item in Model)
                      {
                                               
                        <tr>
                          <td>@item.Id</td>
                          <td>@item.name</td>
                          <td>@item.population</td>
                          <td>@item.capital</td>
                          <td><img src="/countryimage/@item.imageUrl" alt="country" width=50 height=50></td>
                          <td><a href="/Country/Remove/@item.Id" class="btn btn-danger">Sil</a>
                              <a href="/Country/UpdateCountry/@item.Id" class="btn btn-success">Düzenle</a>
                      
                          
                        </tr>
               
                      }
                      </tbody>
                    </table>
                    <br/>
                    <a href="/Country/SaveCountry/" class="btn btn-primary">Yeni Ülke Ekle</a>
                  </div>
                </div>
              </div>

Countries--Cities.WEB/Views/Country/SaveCountry.cshtml
@model Countries__Cities.WEB.Models.CountryViewModel

@{
    ViewData["Title"] = "SaveCountry";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}

@if (ViewBag.Message != null)
{
    <script type="text/javascript">
        window.onload = function () {
            alert('@ViewBag.Message');
        };
    </script>
}  


<div class="col-md-12 grid-margin stretch-card">
                <div class="card">
                  <div class="card-body">
                    <h4 class="card-title">Ülke Ekle</h4>


            <form asp-action="SaveCountry" method="post" asp-controller="Country" enctype="multipart/form-data">

            <div class="form-group">
                <label asp-for="name"></label>
                <input asp-for="name" class="form-control" />
                <span asp-validation-for="name" class="text-danger"></span>
            </div>

             <div class="form-group">
                <label asp-for="population"></label>
                <input asp-for="population" class="form-control" />
                <span asp-validation-for="population" class="text-danger"></span>
            </div>

             <div class="form-group">
                <label asp-for="capital"></label>
                <input asp-for="capital" class="form-control" />
                <span asp-validation-for="capital" class="text-danger"></span>
            </div>

   
             <div class="form-group">
                <label asp-for="image"></label>
                <input type="file" asp-for="image" class="form-control" required/>
                
            </div>


            <div class="form-group">

                <input type="submit" value="Save" class="btn-primary" />

            </div>
        </form>

                    </div>
                </div>
              </div>

Countries--Cities.WEB/Views/Country/UpdateCountry.cshtml
@model Countries__Cities.WEB.Models.CountryViewModel

@{
    ViewData["Title"] = "UpdateCountry";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}


@if (ViewBag.Message != null)
{
    <script type="text/javascript">
        window.onload = function () {
            alert('@ViewBag.Message');
        };
    </script>
}  


<div class="col-md-12 grid-margin stretch-card">
                <div class="card">
                  <div class="card-body">
                    <h4 class="card-title">Ülke Düzenle</h4>


            <form asp-action="UpdateCountry" method="post" asp-controller="Country" enctype="multipart/form-data">

             <input type="hidden" asp-for="Id" />

             <input type="hidden" asp-for="imageUrl" value="@ViewBag.imageUrl" />

            <div class="form-group">
                <label asp-for="name"></label>
                <input asp-for="name" class="form-control" />
                <span asp-validation-for="name" class="text-danger"></span>
            </div>

             <div class="form-group">
                <label asp-for="population"></label>
                <input asp-for="population" class="form-control" />
                <span asp-validation-for="population" class="text-danger"></span>
            </div>

             <div class="form-group">
                <label asp-for="capital"></label>
                <input asp-for="capital" class="form-control" />
                <span asp-validation-for="capital" class="text-danger"></span>
            </div>

   
             <div class="form-group">
                <label asp-for="image"></label>
                <input type="file" asp-for="image" class="form-control"/>
                
            </div>


            <div class="form-group">

                <input type="submit" value="Update" class="btn-primary" />

            </div>
        </form>

                    </div>
                </div>
              </div>